title:              Today I Learned (TIL) Physics
email:              vivekjha@outlook.in
description:        Today I Learned (TIL) Physics
author:             Vivek Kumar Jha
baseurl:            "/tilphysics"
url:                "https://viveikjha.github.io/tilphysics"

# Social Profiles
twitter_username:   drvivekjha
github_username:    viveikjha
facebook_username:  vivekjha.bhu
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
